### ISSUE TITLE
Fail2ban still failing on Travis CI

### ISSUE THREAD

**Issue by back-2-95** [geerlingguy/ansible-role-security#26]
I have hangout still with fail2ban even if I have the latest version of your centos7 docker image where this was fixed: https://github.com/geerlingguy/ansible-role-security/issues/21

```
TASK [geerlingguy.security : Ensure fail2ban is running and enabled on boot.] **
```

**Comment by back-2-95** [comment]
Interesting, if I skip security role for my travis test I get now the same for Postfix:

```
TASK [geerlingguy.postfix : Ensure postfix is started and enabled at boot.] ****
```

**Comment by geerlingguy** [comment]
@back-2-95 - can you tell me which Docker image it is? You might need to run a Docker pull on it to make sure you have the latest. I just updated my Ansible centos7 image a day or two ago because of the exact same issue (systemd got out of date).

**Comment by back-2-95** [comment]
Yes, I have docker pull on my `before_install` for a forked version of `geerlingguy/docker-${distro}-ansible:latest`. I need to check if building that again helps.

**Comment by geerlingguy** [comment]
@back-2-95 - Ah yes, in that case, you need to go into Docker Hub and trigger a new build manually—every few months, when there's a major `systemd` package update in CentOS, this seems to happen again. The problem is the first thing you install will trigger a `systemd` restart internally, and once that happens, the Docker container's ability to start and stop services goes haywire (at least until you do a `docker stop && docker start`—which can't easily be done when doing CI testing inside Travis!).

**Comment by back-2-95** [comment]
I tried using your original build and it worked.
Weird 'coz I had my forked image build yesterday.
Well this still fixes it.

**Comment by geerlingguy** [comment]
Strange! Well, I'll close this out, and if you find anything else helpful, please post back here. Thanks!

**Comment by back-2-95** [comment]
Yes thanks!

We needed to force Quay to build our forked version to get systemd updated.
